version: "3.8"
services:
  oneframe:
    image: "paidyinc/one-frame:latest"
    ports:
      - 9090:8080

  forex:
    image: "forex/forex:latest"
    ports:
      - 8080:8080
    environment:
      - ONEFRAME_HOST=oneframe
      - ONEFRAME_PORT=8080
      - ONEFRAME_API_KEY=10dc303535874aeccc86a8251e6992f5
      - ONEFRAME_UPDATE_TIMEOUT=300 seconds
    depends_on:
      - oneframe
